### ISSUE TITLE
Database probelms with the Dish table

### ISSUE THREAD

**Issue by QuinNiu** [BUMETCS673/project-f23team3#6]
Source code: 
class Dish_Label(Base):
    dish_id = db.Column(db.Integer, db.ForeignKey('Dish.id'), primary_key=True)
    label = db.Column(db.Text, primary_key=True)

Error:
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'dish__label.dish_id' could not find table 'Dish' with which to generate a foreign key to target column 'id'

**Comment by songzhuoru** [comment]
The problem has been solved during the code refactoring.
